#! /bin/bash

echo "turning off bed led";
curl -X PUT https://developer-api.govee.com/v1/devices/control \
	-H "Govee-API-Key: $GOVEE_API_KEY" \
	-H 'Content-Type: application/json' \
	-d '
{
	"device": "'"$GOVEE_BED_LED_MAC_ADDRESS"'",
	"model": "'"$GOVEE_BED_LED_MODEL"'",
	"cmd": {
		"name": "turn",
		"value": "off"
	}
}' \
| json_pp;
